### ISSUE TITLE
Linter always returns "No lint results."

### ISSUE THREAD

**Issue by jonadsimon** [trezona-lecomte/SublimeLinter-contrib-sqlint#2]
I followed these steps:
1. Installed `sqlint` using `gem install sqlint`
2. Installed `SublimeLinter-contrib-sqlint` plugin using `Package Install` (already have SublimeLinter installed
3. Updated my `SublimeLinter.sublime-settings` file to check the appropriate paths and files (see below)

**When I intentionally introduce errors into a `test.sql` file nothing shows up in the gutter, and when I run `SublimeLinter: Show All Errors` it returns `No lint results.`**. However when I run `sqlint test.sql` in the terminal the errors *are* detected correctly

My `SublimeLinter.sublime-settings` User Settings file looks like this, and correctly points to the `sqlint` executable:
```
// SublimeLinter Settings - User
{
	"paths": {
	    "linux": [],
	    "osx": [
	        "~/.rbenv/shims"
	    ],
	    "windows": []
	},
  "linters": {
      "sqlint": {
          "selector": "*.sql"
			},
      "rubocop": {
          "selector": "*.rb"
			}
	},
}
```

I am running:
* OSX Sierra v10.12.6
* Sublime v3.1.1
* SublimeLinter v4.8.0
* SublimeLinter-contrib-sqlint v1.0.0
* sqlint v0.1.8

**Comment by trezona-lecomte** [comment]
Hi @StarvingMathematician, this looks to be an issue with your configuration. The `selector` field wants `"source.sql"` rather than `"*.sql"`, as per the [docs](http://www.sublimelinter.com/en/stable/linter_settings.html#selector). 

I've tried your config with this change and it works, so let me know how you get on.
